---
- name: Install Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Install Docker on Debian based systems
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker on Arch Linux based systems
      pacman:
        name: docker
        state: present
      when: ansible_os_family == "Archlinux"

    - name: Install docker-compose on Debian based systems
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"

    - name: Install docker-compose on Arch Linux based systems
      pacman:
        name: docker-compose
        state: present
      when: ansible_os_family == "Archlinux"

    - name: Add Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Kubernetes on Debian based systems
      apt:
        name:
          - kubeadm
          - kubectl
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy installKubeArch.sh to remote
      copy:
        src: "{{ playbook_dir }}/installKubeArch.sh"
        dest: "/tmp/installKubeArch.sh"
        mode: '0755'

    - name: Ensure installKubeArch.sh is executable
      file:
        path: "/tmp/installKubeArch.sh"
        mode: '0755'

    - name: Run custom script to install Kubernetes on Arch based systems
      shell: "bash -l -c '/tmp/installKubeArch.sh'"
      become: no
      register: script_output
      when: ansible_os_family == "Archlinux"

    - name: Print script output
      debug:
        var: script_output.stdout_lines
      when: ansible_os_family == "Archlinux"